- .vscode/launch.json
- go.mod
- go.sum
- internal/stackql/primitivebuilder/builder.go
- internal/stackql/primitivebuilder/nop.go
- accomodate column display for `DESCRIBE` on polymorphic `SELECT`.
- move all `NopBuilder` into single file.
> polymorphic-describe

- .vscode/launch.json
- go.mod
- go.sum
- internal/stackql/handler/handler.go
- internal/stackql/planbuilder/primitive_generator.go
- test/robot/functional/stackql_from_cmd_line.robot
- Show providers includes current version.
> enriched-show-providers

- go.mod
- go.sum
- Bugfix for defective `nil` check.
> nil-check-safety

- test/registry/src/k8s/v0.1.0/services/core_v1.yaml
- Test input includes example server protocol variable.
> protocol-server-variable

- .vscode/launch.json
- internal/stackql/astvisit/placeholder_param_extract.go
- internal/stackql/astvisit/specialisations.go
- internal/stackql/astvisit/table_alias_pairing.go
- internal/stackql/parserutil/parser_util.go
- internal/stackql/planbuilder/plan_builder.go
- internal/stackql/planbuilder/statement_analyzer.go
- internal/stackql/util/plan_utility.go
- test/registry/src/aws/v0.1.0/services/ec2.yaml
- test/tls/scratchpad/.gitignore
- Placeholder parameters implemented to support heirarchy search.
- Dynamic insert logic implemented.
- AWS insert integration test now uses dynamic insert.
> eager-parameter-placeholders-and-dynamic-insert

- go.mod
- go.sum
- internal/stackql/cmd/shell.go
- internal/stackql/resultutil/resultutil.go
- internal/stackql/util/plan_utility.go
- Improved, conformed error messages.
> improved-error-surfacing

- internal/stackql/httpbuild/request.go
- internal/stackql/httpmiddleware/httpmiddleware.go
- internal/stackql/provider/generic.go
Summary:
- Improved HTTP logging for when `--http.log.enabled` parameter is supplied.
> simple-logging-in-place

- .vscode/launch.json
- Dockerfile
- README.md
- internal/stackql/metadatavisitors/requestvisitors.go
- test/assets/expected/simple-templating/insert-bigquery-datasets.iql
- test/robot/functional/stackql_from_cmd_line.robot
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/lib/StackQLInterfaces.py
- vol/stackql/.gitignore
- Dockerfile included, plus some tech howto.
- Refactor of functional tests, which will eventually support dockerised testing.
- Bugfix for circular reference hansling in `SHOW INSERT...`; was exposed through `show insert into google.bigquery.routines;`.
> docker-starter

- .vscode/launch.json
- go.mod
- go.sum
- internal/stackql/primitivebuilder/single_select_acquire.go
- test/registry/src/aws/v0.1.0/services/ec2.yaml
Summary:
- Incorporate `go-openapistackql` with hotfix.
- `aws.ec2` doc expansion, manually tested.
> bugfix-aws-expand

- .vscode/launch.json
- go.mod
- go.sum
- test/registry/src/aws/v0.1.0/services/ec2.yaml
- test/robot/functional/stackql_from_cmd_line.robot
- test/robot/lib/stackql_context.py
- Improved `xpath` -> relation schema search support.
- Robot test coverage.
> aws-expanded-further

- .vscode/launch.json
- internal/stackql/planbuilder/plan_builder.go
- internal/stackql/planbuilder/statement_analyzer.go
- test/registry/src/aws/v0.1.0/services/cloud_control.yaml
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/lib/stackql_context.py
- Support for request body parameters and server parameters in `delete`.
- Robot test coverage for above via `delete from... aws.cloud_control.resources...`.
> request-body-shims

- go.mod
- go.sum
- Improved http response error handling.
- Via `go-openapistackql`.
> uplift-http-response-error-handling

- .vscode/launch.json
- go.mod
- go.sum
- internal/stackql/astvisit/placeholder_param_extract.go
- internal/stackql/httpbuild/request.go
- internal/stackql/methodselect/methodselect.go
- internal/stackql/parserutil/parser_util.go
- internal/stackql/planbuilder/plan_builder.go
- internal/stackql/planbuilder/primitive_generator.go
- internal/stackql/planbuilder/statement_analyzer.go
- internal/stackql/taxonomy/hierarchy.go
- internal/stackql/util/plan_utility.go
- test/registry/src/aws/v0.1.0/services/cloud_control.yaml
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/lib/stackql_context.py
- Simple `update` functionality in place, with static parameters only.
- Robot test for `update` on `aws.cloud_control.resources`.
> first-update-in-place

- test/registry/src/aws/v0.1.0/services/iam.yaml
- Improved response parsing for `aws.iam`.
- Improved resource nomenclature for `aws.iam`.
> improved-iam-coverage

- .github/workflows/go.yml
- Dockerfile
- docker-compose.yml
- internal/stackql/cmd/shell.go
- internal/stackql/writer/writer.go
- test/.stackql/.gitignore
- test/robot/README.md
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/functional/stackql_sessions.robot
- test/robot/lib/ShellSession.py
- test/robot/lib/StackQLInterfaces.py
- test/robot/lib/stackql_context.py
- vol/logs/.gitignore
- `stackql shell` now testable with robot.
- Leverages python subprocess lib.
- Currently not working in windows.
> primitive-session-testing-pattern-working

- internal/stackql/dto/dto.go
- Misnamed input parameter corrected.
> input-param-bugfix

- docs/GC_cache_concurrency.md
- internal/stackql/dto/dto.go
- internal/stackql/provider/generic.go
- Hotfix for auth config mutation at runtime.
- No tests added.
> auth-mutation-defect

- .github/workflows/go.yml
- README.md
- docker-compose-credentials.yml
- docker-compose-dev.yml
- docker-compose.yml
- test/robot/functional/stackql.resource
- `docker compose` uplift.
- Recently discovered schema mutability bug fix.
> schema-mutability-scenario

- docs/views.md
- internal/stackql/httpbuild/exec_context.go
- internal/stackql/httpbuild/http_armoury.go
- internal/stackql/httpbuild/http_armoury_params.go
- internal/stackql/httpbuild/request.go
- internal/stackql/internaldto/exec_payload.go
- internal/stackql/internaldto/http.go
- internal/stackql/planbuilder/primitive_generator.go
- internal/stackql/planbuilder/statement_analyzer.go
- internal/stackql/primitivebuilder/graphql_single_select_acquire.go
- internal/stackql/primitivebuilder/single_select_acquire.go
- internal/stackql/provider/generic.go
- internal/stackql/provider/provider.go
- More encapsulation.
- High level views readme added to docs.
> view-preparation

- .github/workflows/go.yml
- Dockerfile
- internal/stackql/handler/handler.go
- test/robot/functional/stackql.resource
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/functional/stackql_sessions.robot
- test/robot/lib/StackQLInterfaces.py
- Added automated robot testing for WSL.
> wsl-testing-pattern

- .github/workflows/go.yml
- README.md
- test/README.md
- test/robot/functional/stackql.resource
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/functional/stackql_sessions.robot
- test/robot/lib/StackQLInterfaces.py
- Expanded WSL robot tests.
- Expanded Docker robot tests.
> testing-broadened

- .vscode/launch.json
- internal/stackql/astanalysis/annotatedast/annotated_ast.go
- internal/stackql/astanalysis/earlyanalysis/ast_expand.go
- internal/stackql/astindirect/indirect.go
- internal/stackql/astvisit/from_rewrite.go
- internal/stackql/astvisit/query_rewriting.go
- internal/stackql/dependencyplanner/dependencyplanner.go
- internal/stackql/drm/drm_cfg.go
- internal/stackql/drm/prepared_statement_ctx.go
- internal/stackql/drm/prepared_statement_parameterized.go
- internal/stackql/drm/relayed_column_metadata.go
- internal/stackql/drm/standard_column_metadata.go
- internal/stackql/internaldto/view_dto.go
- internal/stackql/primitivebuilder/dependent_recursive.go
- internal/stackql/primitivebuilder/single_select.go
- internal/stackql/primitivebuilder/sub_tree_builder.go
- internal/stackql/primitivecomposer/primitive_composer.go
- internal/stackql/primitivegenerator/primitive_generator.go
- internal/stackql/relationaldto/relational_column.go
- internal/stackql/router/parameter_router.go
- internal/stackql/sqldialect/postgres.go
- internal/stackql/sqldialect/sqlite.go
- internal/stackql/sqlrewrite/sqlrewrite.go
- internal/stackql/tablemetadata/extended_table_metadata.go
- test/mockserver/expectations/static-github-expectations.json
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- View logic implemented as inlined, aliased subqueries.
- Dataflow dependencies enforced through builder, sophisticated analysis unnecessary.
- Robot test updated.
> simplest-view-semantics

- .vscode/launch.json
- internal/stackql/astanalysis/annotatedast/annotated_ast.go
- internal/stackql/astanalysis/earlyanalysis/ast_expand.go
- internal/stackql/astanalysis/earlyanalysis/first_passes.go
- internal/stackql/astanalysis/routeanalysis/select_route_analysis.go
- internal/stackql/astanalysis/selectmetadata/select_metadata.go
- internal/stackql/astvisit/query_rewriting.go
- internal/stackql/dependencyplanner/dependencyplanner.go
- internal/stackql/drm/drm_cfg.go
- internal/stackql/drm/prepared_statement_args.go
- internal/stackql/drm/prepared_statement_ctx.go
- internal/stackql/parserutil/parser_util.go
- internal/stackql/planbuilder/plan_builder.go
- internal/stackql/planbuilderinput/plan_builder_input.go
- internal/stackql/primitivebuilder/union.go
- internal/stackql/primitivecomposer/primitive_composer.go
- internal/stackql/primitivegenerator/primitive_generator.go
- internal/stackql/primitivegenerator/select.go
- internal/stackql/primitivegenerator/statement_analyzer.go
- internal/stackql/router/parameter_router.go
- internal/stackql/router/table_routing.go
- internal/stackql/sqldialect/sql/postgres/sqlengine-setup.ddl
- internal/stackql/sqldialect/sql/sqlite/sqlengine-setup.ddl
- internal/stackql/tablemetadata/extended_table_metadata.go
- test/registry/src/aws/v0.1.0/services/ec2.yaml
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Recursive `Select` AST node analysis: 
- Some parameter routing. 
- `ON` condition data flow analysis. 
- Composable, encapsulated object for this phase.
- Supports pattern for parameter routing into indirects.
- Views may now contain `UNION` queries:
- Inclusive of integration testing.
> view-parameter-routing

- .github/workflows/go.yml
- README.md
- internal/stackql/cmd/root.go
- Default registry served over DENO.
> registry-serving-migration

- .github/workflows/go.yml
Summary:
- `mingw` version configurable.
> mingw-version-configurable

- .github/workflows/go.yml
- .vscode/launch.json
- docs/auth.md
- docs/developer_guide.md
- go.mod
- go.sum
- internal/stackql/dto/dto.go
- internal/stackql/provider/auth_util.go
- internal/stackql/provider/generic.go
- pkg/awssign/aws_sign.go
- pkg/azureauth/default_token.go
- test/robot/integration/stackql.resource
- test/robot/integration/stackql_integration_from_cmd_line.robot
- test/robot/integration/tmp/.gitignore
- test/robot/lib/StackQLInterfaces.py
- test/robot/lib/stackql_context.py
- `azure` default credentials auth.
- Applies to both individual user and Service Principal authentication.
- Robot integration test case in place.
> azure-default-auth-flow-working

- internal/stackql/astvisit/query_rewriting.go
- internal/stackql/constants/constants.go
- internal/stackql/datasource/sql_datasource/generic.go
- internal/stackql/datasource/sql_datasource/sql_datasource.go
- internal/stackql/dependencyplanner/dependencyplanner.go
- internal/stackql/sql_system/postgres.go
- internal/stackql/sql_system/sqlite.go
- test/registry/src/sni/v0.1.0/provider.yaml
- `snowflake` static tables defined a la `postgres` external pattern.
- Special cases for `snowflake` casing and quoting rules.
- Manually tested only, as per below screen capture.
> snowflake-information-schema-experiment

- internal/stackql/config/config.go
- internal/stackql/parse/parse.go
- internal/stackql/primitivebuilder/delete.go
- internal/stackql/primitivebuilder/exec.go
- internal/stackql/primitivebuilder/insert.go
- internal/stackql/primitivebuilder/util.go
- test/assets/expected/simple-insert/bq-datasets/insert-dependent-bq-datasets.txt
- test/registry/src/pgi/v0.1.0/provider.yaml
- test/registry/src/sni/v0.1.0/provider.yaml
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Amended obsolete prefix on parser errors.
- Amended misleading message for non-polled asynchronous operations.
- Prevent error logging by default.
> spurious-messaging-patches

- internal/stackql/parserutil/parser_util.go
- internal/stackql/sql_system/postgres.go
- internal/stackql/sql_system/sqlite.go
- test/assets/expected/views/select-cross-cloud-disks.json
- test/robot/functional/stackql_sessions.robot
- test/robot/lib/stackql_context.py
- Supports view column aliasing.
> view-column-aliasing

- internal/stackql/astanalysis/earlyanalysis/ast_expand.go
- internal/stackql/astanalysis/earlyanalysis/first_passes.go
- internal/stackql/constants/constants.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- version.txt
- Views blocked from citing other views as a tactical measure.
> view-depth-limitation

- internal/stackql/primitivebuilder/delete.go
- AWS EC2 Volume delete flow supported.
> aws-volume-delete

- test/assets/expected/azure/billing/billing-account-list.json
- test/mockserver/README.md
- test/mockserver/expectations/static-azure-expectations.json
- test/registry/src/azure/v0.1.0/services/billing.yaml
- test/robot/functional/stackql_sessions.robot
- test/robot/lib/stackql_context.py
- Added regression test for `azure.billing.accounts` query that exposed `go-openapistackql` bug.
> added-regression-test-for-path-query-routing

- .github/workflows/go.yml
- Skip integration testing in absence of GH secrets.
- Supports forking PR flow.
- Supports community contributions.
N/A
Please pay attention for the `Run robot integration tests` steps in GH actions, and in particular that inside the `WSL test` job should always run whenever GH secrets are available.
N/A
No technical debt introduced in this change.
> support-fork-pr-flow

- docs/high-level-design.md
- Amended broken URL that resulted in `404`.
N/A
There are no automated tests for this sort of fix at the present time.
This is simply fixing a broken hyperlink in a README, and at this time there is not automated testing pattern for same.
This change does not introduce technical debt.
> fixed-broken-link

- README.md
- licenses/README.md
- version.txt
- Minor Version 5.
- Amend doco to better cite `psql-wire`.
N/A.
N/A.
N/A.
> minor-version-5

- .github/workflows/go.yml
- .github/workflows/lint.yml
- .golangci.yml
- Add `actionlint` action.
- Whitelist additional go linters.
Closes https://github.com/stackql/stackql/issues/155
N/A.
> ci-action-lint

- .github/workflows/lint.yml
This is simply correcting the branch for push action on the action linter.
> corrected-branch

- .github/workflows/lint.yml
- .vscode/launch.json
- docker-compose-externals.yml
- docs/case-studies/dashboards.md
- internal/stackql/astanalysis/earlyanalysis/first_passes.go
- internal/stackql/astanalysis/routeanalysis/select_route_analysis.go
- internal/stackql/cmd/root.go
- internal/stackql/data_staging/input_data_staging/input_data_staging.go
- internal/stackql/dbmsinternal/dbmsinternal.go
- internal/stackql/internal_data_transfer/internaldto/heirarchy_identifiers.go
- internal/stackql/router/annotations_machinery.go
- internal/stackql/router/table_routing.go
- internal/stackql/tablemetadata/extended_table_metadata.go
- internal/stackql/tablemetadata/hierarchy_objects.go
- internal/stackql/taxonomy/hierarchy.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/functional/stackql_postgres_housekeeping.robot
- Support for scalar selects.
- More intelligent routing to SQL backends of catalog queries.
- Added robot test `Scalar Select Verify`.
- Added robot test `Select Class Oid`.
- Added robot test `Select Attributes`.
- Added robot test `Select Attribute Metadata`.
- Added robot test `Select Enums Returns Header Only`.
- Lint CICD job rename and tag improvement.
- Added robot test `Scalar Select Verify`.
- Added robot test `Select Class Oid`.
- Added robot test `Select Attributes`.
- Added robot test `Select Attribute Metadata`.
- Added robot test `Select Enums Returns Header Only`.
> dashboard-basics

- go.mod
- go.sum
- test/robot/functional/stackql_from_cmd_line.robot
- Expose required server variables.
- Robot test added `Show Methods including server params AWS`.
N/A.
- Robot test added `Show Methods including server params AWS`.
N/A.
> required-server-variables

- internal/stackql/sqlrewrite/sqlrewrite.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Account for non-determinism of topological sort.
- Added robot test `Left Inner Join Users`.
N/A.
- Added robot test `Left Inner Join Users`.  This just increases coverage on adjacent queries.
N/A.
This change does not introduce technical debt.  However, it must be said that the orchestration of query passes and subsequent serialisation needs work.
> indeterminate-topo-sort

- .vscode/launch.json
- go.mod
- go.sum
- internal/stackql/astformat/ast_format_postgres.go
- internal/stackql/constants/constants.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Added support for `postgres` table valued function `json_array_elements_text`.
- Robot test `SQLite Table Valued Function Plus Projection Returns Expected Results` enhanced and renamed to `Table Valued Function Plus Projection Returns Expected Results`.
N/A.
- Robot test `SQLite Table Valued Function Plus Projection Returns Expected Results` enhanced and renamed to `Table Valued Function Plus Projection Returns Expected Results`.
> postgres-tvf

- docs/wire_protocol.md
- go.mod
- go.sum
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Negative index support for `split_part` over both `postgres` and `sqlite` backends.
- Added robot test `Split Part Simple Invocation Working`.
- Added robot test `Split Part Negative Index Invocation Working`.
N/A.
- Added robot test `Split Part Simple Invocation Working`.
- Added robot test `Split Part Negative Index Invocation Working`.
N/A.
> split-part-conform

- internal/stackql/driver/dependent_simple_integration_test.go
- internal/stackql/responsehandler/responsehandler.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Messages from `exec` type commands now into `stderr`.
- Robot tests migrated to new expectation pattern.
- Amended one unit test to read `stderr`.
N/A.
- Robot tests migrated to new expectation pattern.  
- Eg: `AWS EC2 Volume Update Simple` and many others.
N/A.
> messages-in-stderr

- .github/workflows/build_docker_cross_platform.yml
- Manual intervention to distribute arm64 docker image.
`arm64` docker image successfully pushed as per https://hub.docker.com/layers/stackql/stackql/latest/images/sha256-14e253f213e541f4f086ff23fd001e8b44d98ccb306192148d27332f0e81c042?context=explore
N/A.
No technical debt is introduced in this change.  It is true that we are still exploring safe, maintainable ways for exotic platform distribution.  Some of this may be done in a private repository with self hosted runners, eventually.
> docker-arm-build-and-push

- .github/workflows/go.yml
- Support multi platofrm properly.
N/A.
> docker-buildx-setup

- .github/actionlint.yaml
- Whitelist larger github runner for docker cross compile.
N/A.
Please see [this github actions linting run](https://github.com/stackql/stackql/actions/runs/6287222749).
N/A.
> actionlint-fix

- .vscode/launch.json
- internal/stackql/internal_data_transfer/builder_input/builder_input.go
- internal/stackql/planbuilder/plan_builder.go
- internal/stackql/primitivebuilder/insert_or_update.go
- internal/stackql/primitivebuilder/raw_native_exec.go
- internal/stackql/primitivegenerator/statement_analyzer.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support simple table `UPDATE`.
- Support simple table `DELETE`.
- Added robot test `Table Lifecycle Plus Update Returns Expected Results`.
- Added robot test `Table Lifecycle Plus Delete Returns Expected Results`.
https://github.com/stackql/stackql/issues/207
- Added robot test `Table Lifecycle Plus Update Returns Expected Results`.
- Added robot test `Table Lifecycle Plus Delete Returns Expected Results`.
N/A.
> simple-table-mutations

- .vscode/launch.json
- internal/stackql/astvisit/query_rewriting.go
- internal/stackql/primitivecomposer/primitive_composer.go
- internal/stackql/primitivegenerator/statement_analyzer.go
- internal/stackql/sql_system/postgres.go
- internal/stackql/symtab/symtab.go
- internal/stackql/tablemetadata/extended_table_metadata.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support symbol resolution for join including views.
- View symbol table clobbered all else in prior state.
- Added robot test `Create and Interrogate Materialized View With Aliasing and Name Collision`.
N/A.
- Added robot test `Create and Interrogate Materialized View With Aliasing and Name Collision`.
N/A.
> view-join-symbol-resolution

- .vscode/launch.json
- internal/stackql/astanalysis/earlyanalysis/ast_expand.go
- internal/stackql/astindirect/materialized_view_indirect.go
- internal/stackql/astindirect/physical_table_indirect.go
- internal/stackql/router/parameter_router.go
- internal/stackql/symtab/symtab.go
- internal/stackql/typing/relational_column.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Aliasing for all indirections in symtab.
- Updated robot test `Create and Interrogate Materialized View With Aliasing and Name Collision`.
N/A.
- Updated robot test `Create and Interrogate Materialized View With Aliasing and Name Collision`.
N/A.
> symtab-aliasing

- internal/stackql/handler/handler.go
- Addressed discovered concurrent map write bug.
- Discovered in async query testing for python client lib [here](https://github.com/stackql/pystackql/actions/runs/6515738332/job/17698514492).
Bug stack trace:
```
fatal error: concurrent map writes
goroutine 12 [running]:
github.com/stackql/stackql/internal/stackql/handler.(*standardHandlerContext).GetProvider(0xc00017b800, ***0xc0001a2bd8?, 0xc0001a2bf0?***)
/Users/runner/work/stackql/stackql/internal/stackql/handler/handler.go:259 +0x346
github.com/stackql/stackql/internal/stackql/astanalysis/earlyanalysis.(*indirectExpandAstVisitor).Visit(0xc00051a000, ***0x10[18](https://github.com/stackql/pystackql/actions/runs/6515738332/job/17698514492#step:8:19)89d90?, 0xc000139540?***)
/Users/runner/work/stackql/stackql/internal/stackql/astanalysi …
```
> concurrent-provider-map-writes

- .github/FUNDING.yml
Adding FUNDING file to .github config.
None
Not Applicable
Not applicable
None
> ci(github-actions): adding funding yaml section

- internal/stackql/primitivebuilder/ddl.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Best effort remove `materialized view` book-keeping that was causing bug, in `CREATE OR REPLACE`.
- Added robot test `Create Then Replace and Interrogate Materialized View With Union`.
!Closes https://github.com/stackql/stackql/issues/326
- Added robot test `Create Then Replace and Interrogate Materialized View With Union`.
N/A.
Because this is explicitly best effort at this stage, the lack of atomicity shall not be regarded as technical debt.
> replace-materialized-view-fix

- .vscode/launch.json
- docker-compose.yml
- go.mod
- go.sum
- internal/stackql/netutils/http_proxy.go
- internal/stackql/psqlwire/server.go
- test/robot/functional/stackql_sessions.robot
- test/robot/lib/stackql_context.py
- test/server/mtls/README.md
- `TCP` server to enforce `mTLS` when so configured.
- Added robot test `Acceptable Secure Connection to mTLS Server Returns Success Message`.
- Added robot test `Unacceptable Insecure Connection to mTLS Server Returns Error Message`.
- Added robot test `Acceptable Secure PSQL Connection to mTLS Server With Diagnostic Query Returns Connection Info`.
- Added robot test `Unacceptable Insecure PSQL Connection to mTLS Server Returns Error Message`.
- Abstracted shell for robot testing scenarios.
- Debug tooling improvement.
- Updated `mTLS server` documentation.
N/A.
Technical debt is introduced in this change.  The following tickets have been raised to address same:
- [Shells used in robot tests for piuping ands client / server interactions](https://github.com/stackql/stackql/issues/365).
- …
> mtls-uplift

- .github/workflows/go.yml
- Tag docker images with semver.
> cicd-docker-semver

- test/mockserver/expectations/static-aws-expectations.json
- test/registry/src/aws/v0.1.0/services/pseudo_s3.yaml
- test/robot/functional/stackql_mocked_from_cmd_line.robot
Summary:
- Verify that multiple request body attributes are handled properly by transformation functionality.
- Added robot test `AWS Hybrid Service Cloud Control S3 Bucket Insert Naive Transformed Extended`.
> augment-request-body-alias-intelligence-testing

- internal/stackql/primitivecomposer/primitive_composer.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Describe for `select` views will simply consume the first listed view.
- Added robot test `Describe Works For Multi Views Through Naive Approach`.
- Added robot test `Describe Extended Works For Multi Views Through Naive Approach`.
N/A.
- Added robot test `Describe Works For Multi Views Through Naive Approach`.
- Added robot test `Describe Extended Works For Multi Views Through Naive Approach`.
N/A.
> describe-view-naive

- .github/workflows/go.yml
- go.mod
- go.sum
- internal/stackql/astanalysis/earlyanalysis/first_passes.go
- internal/stackql/astanalysis/routeanalysis/select_route_analysis.go
- internal/stackql/planbuilderinput/plan_builder_input.go
- internal/stackql/primitivegenerator/statement_analyzer.go
- test/mockserver/expectations/static-aws-expectations.json
- test/robot/functional/stackql.resource
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for `union` with exotic dataflow.
- Added robot test `Union of List And Details Dataflow View Works As Exemplified By AWS KMS Key Cloud Control`.
- Update parser.
- Add docker cleanup and debug information to docker build run.  This was required because robot is no longer cleaning up docker containers adequately.
- Adopt robot framework deprecation suggestion for `[Return]` -> `RETURN`.
N/A.
- Added robot test `Union of List And Details Dataflow View Works As Exemplified By AWS KMS Key Cloud Control`.
N/A.
> union-and-ci-uplifted

- .github/workflows/go.yml
- test/robot/lib/stackql_context.py
- Restore long term inactive and bug-ridden `windows` CI.
- `openssl` version pinning for `windows`.
N/A.
The pre-
> restore-windows-ci

- .github/workflows/go.yml
- Upgrade `macos-11` runner to `macos-12`.  This is required to align with [the upccoming `macos-11` deprecation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
N/A.
The testing battery serves as evidence.
N/A.
No technical debt has been added, howver a note has been added to [the versioning and deprecation wiki page](https://github.com/stackql/stackql/wiki/Versioning-and-Deprecation).
> build-macos-12

- internal/stackql/astanalysis/routeanalysis/select_route_analysis.go
- internal/stackql/dataflow/collection.go
- internal/stackql/dataflow/component.go
- internal/stackql/dto/dataflow_cfg.go
- internal/stackql/handler/handler.go
- internal/stackql/router/parameter_router.go
- test/mockserver/expectations/staging.json
- test/mockserver/expectations/static-aws-expectations.json
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/robot/lib/StackQLInterfaces.py
- Support configurable dataflow dependency count properly.
- Added robot test `Materialized View of High Dependency In Clause Split of List And Details Dataflow View Works As Exemplified By AWS KMS Key Cloud Control`.
N/A.
- Added robot test `Materialized View of High Dependency In Clause Split of List And Details Dataflow View Works As Exemplified By AWS KMS Key Cloud Control`.
N/A.
> configurable-dataflow-dependencies

- internal/stackql/dataflow/edge.go
- internal/stackql/dataflow/relation.go
- internal/stackql/dependencyplanner/dependencyplanner.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for static data flows in a multi-dependency dataflow query.
- Added robot test `Static Input Read Many Multi Dependency Multi Dependent Multiple List And Detail Dataflow Works As Exemplified By Azure Vault and Keys and Key Details`.
N/A.
- Added robot test `Static Input Read Many Multi Dependency Multi Dependent Multiple List And Detail Dataflow Works As Exemplified By Azure Vault and Keys and Key Details`.
N/A.
> static-dataflows-in-a-multi-dependency-dataflow

- internal/stackql/parserutil/parser_util.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
Summary:
- Support for string aggreagation on materialized views.
- Added robot test `Sum and String Aggregation on Materialized View as Exemplified By Okta Apps`.
> string-aggregation-mat-views

- internal/stackql/astvisit/query_rewriting.go
- internal/stackql/parserutil/parser_util.go
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for conditional select expressions on table-valued function on materialized view.
- This is useful in ELT and reporting.
- Added robot test `Conditional Column on Table Valued Function in Materialized View Returns Expected Results as Exemplified by Google Firewalls`.
N/A.
- Added robot test `Conditional Column on Table Valued Function in Materialized View Returns Expected Results as Exemplified by Google Firewalls`.
N/A.
The handling of indirection column inference sorely needs an uplift.
> materialized-view-json-each-conditional

- .github/actionlint.yaml
- .github/workflows/go.yml
- Supports `linux` `arm64` builds, producing artifact for same.
- Dependent on pre-existence of a `linux` `arm64` runner,  named `arm-ubuntu-22-04-runner-one`.
Most relevant to discussion rooted at this insightful comment: https://github.com/stackql/stackql/issues/224#issuecomment-2296407980
New builds generate `linux` `arm64` artifact.
N/A.
> linux-arm-builder

- .github/workflows/go.yml
- test/robot/functional/stackql.resource
- test/robot/integration/stackql.resource
- test/robot/lib/stackql_context.py
Summary:
- Automate `deb` package build and retain.
- `robot` tests support preinstalled `stackql`.
- Incorporate robot testing for `deb` package.
- Add both `amd64` `deb` package.
- `deb`-installed `stackql` info `echo`ed post robot tests.
> deb-packqge

- .github/workflows/build.yml
> - remove docker cache.

- .github/workflows/scenario.yaml
- cicd/requirements.txt
- docs/walkthroughs/README.md
- docs/walkthroughs/get-google-accelerator-types.md
- docs/walkthroughs/get-google-vms.md
- test/python/markdown_testing/markdown_testing.py
- Support for simple testing of walkthroughs written in markdown, with annotations.
- Whole table match scenario.
- Nonempty table match scenario.
- Skip testing on files named `README.md`.
- Runnable from CI, with tag of form: `scenario-<stackql_build_run_number>-<anything>`.
N/A.
> demo-md-walkthrough-testing

- .github/workflows/scenario.yaml
- docs/walkthroughs/deploy/README.md
- docs/walkthroughs/readonly/list-aws-instances.md
- docs/walkthroughs/readwrite/README.md
- docs/walkthroughs/readwrite/create-google-vm-webserver.md
- test/python/markdown_testing/markdown_testing.py
- Webserver VM create walkthrough.
Please see the below screen capture of the successful readwrite test for precisely this pull request commit.
N/A.
> readwrite-walkthrough

- .github/workflows/build.yml
- docs/CICD.md
- test/python/tcp_lb.py
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- test/tcp/reverse-proxy/nginx/.gitignore
- test/tcp/reverse-proxy/nginx/README.md
- Dynamically generate `nginx` LB config.
- Expand LB testing.
- Improved documentation for reverse proxied testing.
N/A.
- Robot test `View Tuple Replacement Working As Exemplified by AWS EC2 Instances List and Detail` included in TCP-proxied testing.
- Robot test `Busted Auth Throws Error Then Set Statement Update Auth Scenario Working` included in TCP-proxied testing.
N/A.
> empower-registry-testing

- .github/workflows/scenario.yaml
- cicd/python/tag_parse.py
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Tag parse logic inside this repository.
- Tags reflective of registry current health.
N/A.
The read only, read write, and deploy (empty) walkthroughs pass as expected, per the below screen captures from the private fork.  This demonstrates that migration of tag parse logic is working.
N/A.
> finer-grained-cicd

- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Cater for windows `real` number implementation.
- Skipping robot test `AWS Materialized View and Cast and Multiple Function Query on Resource Costs Exemplifies Cast and Multiple Functions on Materialized Views` for windows only.
- Added robot test `Contains Check AWS Materialized View and Cast and Multiple Function Query on Resource Costs Exemplifies Cast and Multiple Functions on Materialized Views`.
- Skipping robot test `AWS Materialized View and Cast and Multiple Function Query on Resource Costs Exemplifies Cast and Multiple Functions on Materialized Views` for windows only.
- Added robot test `Contains Check AWS Materialized View and Cast and Multiple Function Query on Resource Costs Exemplifies Cast and Multiple Functions on Materialized Views`.
N/A.
No technical debt is …
> bugfix-windows-casting-test

- .github/workflows/build.yml
- .github/workflows/lint.yml
Summary:
- Support for parallel versioned release branches.
- Docker tagging improved on semver and latest tags.
- Enable `stackql/stackql-devel` docker  image zero touch.
> support-meaningful-release-branching

- .github/workflows/build.yml
- Mandatory `actions/cache` upgrade.
- Hack for secret dependent `docker` flow under fork PRs.  Temp fix at best.
N/A.
- No application change; existing test suite continues to pass, indicating no regressions under opaque changes.
N/A.
- A better pattern for `docker` flow on forked PRs is indicated.
> short-term-fix

- .github/workflows/build.yml
Summary:
- Checking if fork PR logic fix.
> hotfix-pr-logic

- internal/stackql/planbuilder/plan_builder.go
In fact, err is incorrect and should be prErr.
> fix: fix the wrong error return value

- internal/stackql/primitivegenerator/statement_analyzer.go
> fix: Fix problematic error returns

- test/robot/functional/stackql_sessions.robot
- Added robot test `Server Stability PG Session Repeat AWS EC2 Select`.
- Added robot test `Server Stability PG Session Repeat AWS EC2 Select`.
N/A.
> server-stability

- test/python/stackql_test_tooling/flask/aws/root_path_cfg.json
- test/python/stackql_test_tooling/flask/aws/templates/describe_volumes_02_page_01.xml
- test/python/stackql_test_tooling/flask/aws/templates/describe_volumes_02_page_02.xml
- test/python/stackql_test_tooling/flask/aws/templates/describe_volumes_02_page_03.xml
- test/registry/src/aws/v0.1.0/services/ec2.yaml
- test/robot/functional/stackql_mocked_from_cmd_line.robot
- No functional change.
- Test with pattern supporting pagination on `xml` -> `json` transformed reponses.
- Added robot test `Select Paginated Projection From Transformed XML Response Body`.
- Amended robot test `Select Star From Transformed XML Response Body` to cover `postgres`.
N/A.
- Added robot test `Select Paginated Projection From Transformed XML Response Body`.
- Amended robot test `Select Star From Transformed XML Response Body` to cover `postgres`.
N/A.
> rewritten-testing-pagination

- test/robot/functional/stackql_mocked_from_cmd_line.robot
- Expanded `xml` tranform testing to cover joins.
- Expanded `xml` tranform testing to cover materialized views.
- Expanded `xml` tranform testing to cover views.
- Added robot test `Select Join Paginated Projection From Transformed XML Response Body`.
- Added robot test `Select View of Join Paginated Projection From Transformed XML Response Body`.
- Added robot test `Select Materialized View of Join Paginated Projection From Transformed XML Response Body`.
- Added robot test `Select Join Paginated Projection From Transformed XML Response Body`.
- Added robot test `Select View of Join Paginated Projection From Transformed XML Response Body`.
- Added robot test `Select Materialized View of Join Paginated Projection From Transformed XML Response Body`.
N/A.
No technical debt is introduced …
> xml-transform-testing-exotic

- cicd/util/01-build-robot-lib.sh
- test/python/stackql_test_tooling/web_service_keywords.py
- Integrate `poetry` into virtual environment, in testing package build workflow.
- Default `cwd` for flask app aggregator better supports testing mobility.
All automated tests continue to pass using amended library.
N/A.
No technical debt is introduced in this channge.
> improve-testing-package

- .github/workflows/build.yml
- Dockerfile
- Add `dnsutils` to docker image.
- Supports useful IAC workloads.
N/A.
Test suite continues to reposrt success.
N/A.
No technical debt is incurred in this change.
> add-dnsutils-to-stackql-image
