stackql/stackql

go.mod
- Consume version of `go-openapistackql` that is present on `main` branch.
=> synced-to-openapistackql-main-branch

internal/stackql/cmd/root.go, internal/stackql/cmd/shell.go, test/functional/stackql_from_cmd_line.robot
- fix yaml escaping for defaulted config directory.  Affected windows only due to `\`.
=> windows-bug

.vscode/launch.json, internal/stackql/output/output.go, test/robot/functional/stackql_from_cmd_line.robot
- Patch regression causing string to be rendered `base64` encoded when `-o json` (json output) in use.
=> json-presentation

.vscode/launch.json, go.mod, go.sum, internal/stackql/cmd/shell.go
- Bugfix for back arrow usage on multiline history items on MAC.  Previously, cursor positioning was errant on MAC.
1. Transcribed an open source cursor-poistioning shim into our `readline` fork.
2. New functionality only used on `OS == "darwin"`.
=> readline-shim-for-mac

.vscode/launch.json, go.mod, go.sum, test/registry/src/aws/v0.1.0/services/ec2.yaml
- Sensible defaults for xml responses supported via `go-openapistackql`.
- Volume insert robot test adjusted to cover the change.
=> aws-enablement

.vscode/launch.json, go.mod, go.sum, internal/stackql/primitivebuilder/single_select_acquire.go, test/registry/src/aws/v0.1.0/services/ec2.yaml, test/robot/functional/stackql_from_cmd_line.robot, test/robot/lib/stackql_context.py
- Support for different `xpath` idioms.
- `describe` works for all select verbs in `aws.ec2`.
=> aws-xpath-support-expansion

internal/stackql/taxonomy/annotation_context.go
- Lazy eval on streaming query parameters so that repeated cached calls do not exhaust http request body.
- TECH DEBT: Need to add integration tests for interactive sessions to cover such things.
=> request-body-lifetime

.vscode/launch.json, go.mod, go.sum
- Generic support for query strings in `openapi3` doc paths, via `go-openapistackql` module.
- Motivated by widespread use thereof inside `azure` provider.
=> query-params-in-paths-generic

test/registry/src/aws/v0.1.0/services/cloud_control.yaml, test/registry/src/aws/v0.1.0/services/ec2.yaml
- Amend incorrect `resource.id` vs `resource.name` transposition.
=> aws-resource-nomenclature

internal/stackql/dto/dto.go, internal/stackql/provider/auth_util.go, internal/stackql/provider/generic.go, pkg/awssign/aws_sign.go
- Support shorthand for api key plus `BEARER` header pattern.
- Obscure AWS keyID; not a secret but just to be exhausitve with identifying data.
=> auth-shorthand

.vscode/launch.json, Dockerfile, docs/examples.md, examples/scripts/python/sqlalchemy_scratchpad.py, internal/stackql/bundle/bundle.go, internal/stackql/cmd/root.go, internal/stackql/constants/constants.go, internal/stackql/dbmsinternal/dbmsinternal.go, internal/stackql/dto/dto.go, internal/stackql/dto/pg_internal_config.go, internal/stackql/entryutil/entryutil.go, internal/stackql/handler/handler.go, internal/stackql/planbuilder/plan_builder.go, internal/stackql/planbuilder/statement_analyzer.go, internal/stackql/primitivebuilder/raw_native_exec.go, internal/stackql/sqlengine/postgres_tcp.go, requirements.txt, test/robot/functional/stackql.resource, test/robot/functional/stackql_sessions_postgres.robot, test/robot/lib/StackQLInterfaces.py, test/robot/lib/sqlalchemy_client.py, test/robot/lib/stackql_context.py
- When using `postgres` as SQL backend, then pass through identifiable housekeeping queries.
- Housekeeping queries can be identified prior to AST visitor passes.
- Queries thus identified can pre-empt subsequent analysis and proceed straight to execution against `postgres`.
- **TECH DEBT**: parser does not assemble viable trees for all housekeeping queries. 
- Existing `postgres` formatter throws panic from this. 
- RCA and fix should be done later but priority lower due to above pre-emption of analysis.
- Previously failing `sqlalchemy` setup added as a robot test.
=> pg-pass-through

internal/stackql/provider/auth_util.go
- Some non-google providers support google service account auth and this change supports the expected flow: 
- googleads 
- googleanalytics 
- googledevelopers 
- googlemybusiness 
- googleworkspace 
- youtube
=> google-dependent-provider-auth

test/robot/functional/stackql_sessions.robot
- Removed blacklisting for `postgres` backend for one of the robot tests for views: 
- Remaining view tests will not work in `postgres` due to case sensitivity / xml issue... addressing same is deferred.
=> whitelist-working-postgres-view-robot-test

.vscode/launch.json, README.md, go.mod, go.sum, internal/stackql/astanalysis/earlyanalysis/ast_expand.go, internal/stackql/astindirect/indirect.go, internal/stackql/astindirect/subquery_indirect.go, internal/stackql/astindirect/view_indirect.go, internal/stackql/constants/constants.go, internal/stackql/dbmsinternal/dbmsinternal.go, internal/stackql/internal_data_transfer/internaldto/heirarchy_identifiers.go, internal/stackql/router/table_routing.go, internal/stackql/taxonomy/hierarchy.go, test/robot/functional/stackql_sessions_postgres.robot, test/robot/lib/stackql_context.py
- Basic support for `postgres` internal subqueries, routed directly to `postgres`.
- Any `postgres` internal tables / views will route the entire query to `postgres`; no hybrids.
- Expanded existing robot test on `google.compute.acceleratorTypes` to verify tables in `stackql_intel` are routable via subquery.
=> support-for-pg-internal-subquery

.vscode/launch.json, docs/dashboards.md, internal/stackql/astanalysis/annotatedast/annotated_ast.go, internal/stackql/astanalysis/earlyanalysis/ast_expand.go, internal/stackql/astindirect/indirect.go, internal/stackql/astindirect/subquery_indirect.go, internal/stackql/astvisit/from_rewrite.go, internal/stackql/dependencyplanner/dependencyplanner.go, internal/stackql/internal_data_transfer/internaldto/heirarchy_identifiers.go, internal/stackql/internal_data_transfer/internaldto/subquery_dto.go, internal/stackql/router/annotations_machinery.go, internal/stackql/router/table_routing.go, internal/stackql/tablemetadata/extended_table_metadata.go, internal/stackql/tablemetadata/hierarchy_objects.go, internal/stackql/taxonomy/annotation_context.go, internal/stackql/taxonomy/hierarchy.go, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for **strictly aliased** subqueries.
- Robot test in place.
Please add deep links to any issues impacted by this PR.
Robot test `Basic Subquery Returns Results`;  will be visible in PR checks.
Please add fulsome explanations for any variations to the checklist.
If zero technical debt results from this change set, then please assert same here.  If, however, technical debt does result from this change set (the **strong** preference is that it does **not**), then please specify and justify.  Once assent is given in the PR conversation for the tech debt to be accrued, please include a link to an issue devoted to the tech debt, in the above issues section.  This should be done prior to merge.
=> subquery-support

docs/CICD.md, docs/developer_guide.md, internal/stackql/astformat/ast_format_postgres.go, internal/stackql/astformat/ast_format_sqlite.go, internal/stackql/sql_system/sql_system.go, test/robot/functional/stackql_mocked_from_cmd_line.robot, test/robot/functional/stackql_sessions.robot, test/robot/lib/StackQLInterfaces.py, test/robot/lib/psycopg_client.py, test/robot/lib/stackql_context.py
- Amend `sqlite` clobbering behaviour where double quoted columns fall back to static string where column not present in table.
- Added robot test `Basic Error Query mTLS Returns Error Message` to verify incorrectly named column throws error in server session.
- Added robot test `PG Session Wrongly Named Column error recovery Azure Compute Table Nomenclature` to verify that the server survives such an input and behaves correctly for a following query.
- Added CICD markdown doc.
- Amended developer guide.
Fixes stackql/stackql#149
- Added robot test `Basic Error Query mTLS Returns Error Message` to verify incorrectly named column throws error in server session.
- Added robot test `PG Session Wrongly Named Column error recovery Azure Compute Table Nomenclature` to verify that the server …
=> expected-behaviour-on-incorrect-column-name-input

.github/pull_request_template.md
Hide the instructions in the PR so contributors do not need to delete the template wording during their PR creation. Users will still see the commented out instructions as the PR text field entry is the raw text and not the rendered markdown.
=> chore: hide instructions in PR template

.github/workflows/go.yml
My last PRs about changing README and PR template both triggered the long `.github/workflows/go.yml` workflow which takes some time and would presumably consume many Actions minutes. To reduce wastage of minutes we can skip running the workflow if only `.md` files have changed.
=> ci: do not run build workflow on markdown file changes

.github/workflows/go.yml, docs/developer_guide.md, internal/stackql/primitivegraph/dag.go, test/robot/functional/stackql.resource, test/robot/lib/StackQLInterfaces.py
- Concurrent execution now possible, configurable with `--execution.concurrency.limit`.  Set to any positive integer for concrete limit, `-1` for max aggressive.  Default remains `1`.
- Reset the graph so that cached queries behave acceptably.
- Added aggressive concurrency testing robot run.
N/A.
Please see the github action step `Run robot mocked functional tests with aggressive concurrency`.
N/A.
No technical debt is introduced by this change.
=> plan-execution-concurrency-uplift

.vscode/launch.json, internal/stackql/astanalysis/earlyanalysis/first_passes.go, internal/stackql/astformat/ast_format_postgres.go, internal/stackql/primitivebuilder/ddl.go, test/registry/src/aws/v0.1.0/services/pseudo_s3.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for `json_extract_path_text` function inside views for `postgres` backend.
- Robot test `Filtered Projection Resource Level View of Cloud Control Resource Returns Expected Result` now runs against `postgres` backend.
- Robot test `Filtered Star Resource Level View of Cloud Control Resource Returns Expected Result` now runs against `postgres` backend.
- Robot test `Filtered and Parameterised Projection Resource Level View of Cloud Control Resource Returns Expected Result` now runs against `postgres` backend.
- Robot test `Filtered and Parameterised Star Resource Level View of Cloud Control Resource Returns Expected Result` now runs against `postgres` backend.
- Robot test `Describe View of Cloud Control Resource Returns Expected Result` now runs against `postgres` backend.
N/A.
- …
=> postgres-json-views

internal/stackql/cmd/root.go, internal/stackql/dto/dto.go, internal/stackql/dto/runtime_ctx.go, internal/stackql/entryutil/entryutil.go, internal/test/stackqltestutil/locator.go, pkg/preprocessor/preprocessor.go, test/assets/expected/env-var-input/env-var-input-expected.iql, test/assets/input/env-var-input/env-var-input.iql, test/assets/input/env-var-input/vars.jsonnet, test/robot/functional/stackql_from_cmd_line.robot, test/robot/lib/StackQLInterfaces.py, test/robot/lib/stackql_context.py
- Support for JSONNET external variables.
- Robot test added `JSONNET Plus Env Vars`.
You can run this manually from the repository root with:
```bash
/path/to/stackql exec -i $(pwd)/test/assets/input/env-var-input/env-var-input.iql  --var project=stackql-demo --var region=australia-southeast1 --iqldata $(pwd)/test/assets/input/env-var-input/vars.jsonnet --dryrun -o text -H
```
N/A.
- Robot test added `JSONNET Plus Env Vars`.
N/A.
No technical debit is added in this change.
=> jsonnet-external-variables

.vscode/launch.json, internal/stackql/astvisit/query_rewriting.go, internal/stackql/parserutil/column_handle.go, internal/stackql/parserutil/parser_util.go, internal/stackql/typing/relational_column.go, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Aggregation of star on views.
- `COUNT(*)` supported.
- Added robot test `Basic Count Star From View Returns Expected Result`.
- Added robot test `Basic Aliased Count Star From View Returns Expected Result`.
N/A.
- Added robot test `Basic Count Star From View Returns Expected Result`.
- Added robot test `Basic Aliased Count Star From View Returns Expected Result`.
N/A.
=> star-agg-on-views

.vscode/launch.json, go.mod, go.sum, internal/stackql/astvisit/from_rewrite.go, internal/stackql/parserutil/parser_util.go, internal/stackql/primitivegenerator/select.go, test/mockserver/expectations/static-gcp-expectations.json, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Parser support for sqlite table valued (cardinality expansion) function `json_each`.
- Parser support for view and table modifiers.
- Added robot test `SQLite Table Valued Function Plus Projection Returns Expected Results`.
N/A.
- Added robot test `SQLite Table Valued Function Plus Projection Returns Expected Results`.
N/A.
No technical debt is introduced in this change.  However, the existing flawed approach in [the from clause rewriter](https://github.com/stackql/stackql/blob/4f67f7fc004636740aa8a75cae7110e422c484c7/internal/stackql/astvisit/from_rewrite.go#L634) is accentuated and, accordingly, a `//TODO` has been added.
=> cardinality-expansion-function

.vscode/launch.json, go.mod, go.sum, internal/stackql/astanalysis/annotatedast/annotated_ast.go, internal/stackql/astanalysis/earlyanalysis/ast_expand.go, internal/stackql/astindirect/indirect.go, internal/stackql/astindirect/materialized_view_indirect.go, internal/stackql/astindirect/physical_table_indirect.go, internal/stackql/astindirect/select_indirect.go, internal/stackql/astvisit/internally_routable_typing.go, internal/stackql/astvisit/query_rewriting.go, internal/stackql/dependencyplanner/dependencyplanner.go, internal/stackql/drm/drm_cfg.go, internal/stackql/internal_data_transfer/builder_input/builder_input.go, internal/stackql/internal_data_transfer/internaldto/heirarchy_identifiers.go, internal/stackql/parserutil/parser_util.go, internal/stackql/planbuilder/plan_builder.go, internal/stackql/primitivebuilder/ddl.go, internal/stackql/primitivebuilder/insert_into_physical_table.go, internal/stackql/primitivebuilder/insert_or_update.go, internal/stackql/primitivegenerator/select.go, internal/stackql/primitivegenerator/statement_analyzer.go, internal/stackql/sql_system/postgres.go, internal/stackql/sql_system/sql_system.go, internal/stackql/sql_system/sqlite.go, internal/stackql/tablemetadata/extended_table_metadata.go, internal/stackql/taxonomy/hierarchy.go, internal/stackql/typing/generic_typing_config.go, internal/stackql/typing/standard_column_metadata.go, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for `CREATE TABLE`.
- Support for `INSERT INTO` physical tables.
- Support for `DROP TABLE`.
- Added robot test `Insert All Simple Patterns Into Embedded Table Then Projection Returns Expected Results`.
- Added robot test `Table Lifecycle Returns Expected Results`.
- Updated robot test `Create Table Scenario Working`.
https://github.com/stackql/stackql/issues/207
- Added robot test `Insert All Simple Patterns Into Embedded Table Then Projection Returns Expected Results`.
- Added robot test `Table Lifecycle Returns Expected Results`.
- Updated robot test `Create Table Scenario Working`.
N/A.
=> table-lifecycle-simple

examples/scripts/python/sqlalchemy_scratchpad.py, test/robot/functional/stackql_sessions.robot, test/robot/functional/stackql_sessions_postgres.robot, test/robot/lib/psycopg2_client.py, test/robot/lib/psycopg_client.py, test/robot/lib/sqlalchemy_client.py
- Changed `psycopg3` client to support queries that do not return results.
- Changed `psycopg2` client to support queries that do not return results.
- Changed `sqlalchemy` client to support queries that do not return results.
- Added robot test `PG Session Materialized View Lifecycle`.
- Added robot test `PG Session V2 Materialized View Lifecycle`.
- Added robot test `SQLAlchemy Session Materialized View Lifecycle`.
- This change adds extra capabilities to the python testing client libs, which are *de facto* reference implementations for third party tooling to emulate.
N/A.
- Added robot test `PG Session Materialized View Lifecycle`.
- Added robot test `PG Session V2 Materialized View Lifecycle`.
- Added robot test `SQLAlchemy Session Materialized View Lifecycle`.
N/A.
No technical debt …
=> changed-python-client-behaviour

internal/stackql/acid/binlog/log.go, internal/stackql/acid/binlog/log_test.go, internal/stackql/acid/transact/best_effort_coordinator.go, internal/stackql/acid/transact/lazy_coordinator.go
Closes #291 
```
$ go test -cover -tags json1,sqleanall  ./...
?       github.com/stackql/stackql/internal/stackql/acid/acid_dto       [no test files]
ok      github.com/stackql/stackql/internal/stackql/acid/binlog 0.002s  coverage: 100.0% of statements
?       github.com/stackql/stackql/internal/stackql/acid/operation      [no test files]
?       github.com/stackql/stackql/internal/stackql/acid/transact       [no test files]
?       github.com/stackql/stackql/internal/stackql/acid/txn_context    [no test files]
?       github.com/stackql/stackql/internal/stackql/astanalysis/annotatedast    [no test files]
?       github.com/stackql/stackql/internal/stackql/astanalysis/earlyanalysis   [no test files]
?       github.com/stackql/stackql/internal/stackql/astanalysis/routeanalysis   [no test …
```
=> Unit tests for binlog

internal/stackql/logging/logging.go, internal/stackql/logging/logging_test.go
Added unit testing for ```internal/stackql/logging``` package
Fix issue [#240](https://github.com/stackql/stackql/issues/240)
=> feat(unit-test): add unit test for package logging

internal/stackql/acid/txn_context/txn_context_test.go, internal/stackql/acid/txn_context/txn_coordinator_context_test.go
We are adding basic unit tests to cover function definitions in package `txn_context`
We are keeping test files under package name `txn_package_test` on the lines on `driver_test` package
NOTE for reviewers: This contribution is for hactoberfest credit please label it so. Thanks!
fixes #294 
```go
(base) ➜  txn_context git:(main) pwd              
/Users/i332719/work/git/github.com/stackql/internal/stackql/acid/txn_context
(base) ➜  txn_context git:(main) go test -v -cover
=== RUN   TestNewTransactionContext
--- PASS: TestNewTransactionContext (0.00s)
=== RUN   TestNewTransactionCoordinatorContext
--- PASS: TestNewTransactionCoordinatorContext (0.00s)
PASS
github.com/stackql/stackql/internal/stackql/acid/txn_context    coverage: 100.0% of statements
ok …
```
=> [294] Add unit testing for package txn_context

internal/stackql/garbagecollector/garbagecollector_test.go
Added unit testing for `internal/stackql/garbagecollector` pacakge
Fixes #230
=> Add unit testing for `garbagecollector` package

internal/stackql/astvisit/param_extract.go, internal/stackql/dataflow/collection.go, internal/stackql/dataflow/vertex.go, internal/stackql/dependencyplanner/dependencyplanner.go, internal/stackql/parserutil/parameter_metadata.go, internal/stackql/primitivegenerator/statement_analyzer.go, internal/stackql/router/parameter_router.go, internal/stackql/sqlrewrite/sqlrewrite.go, internal/stackql/tablemetadata/extended_table_metadata.go, internal/stackql/taxonomy/annotation_context.go, test/mockserver/expectations/static-gcp-expectations.json, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for scalare `IN` subclauses inside `WHERE` clause, for filtering and parameters.
- Added robot test `Select With IN Scalars inside WHERE Clause Returns Expected Result`.
- Added robot test `Select With Server Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
- Added robot test `Select With Path Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
- Distributed hack to suppress contol paramater expansion.
#329 
- Added robot test `Select With IN Scalars inside WHERE Clause Returns Expected Result`.
- Added robot test `Select With Server Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
- Added robot test `Select With Path Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
N/A.
The …
=> simplest-possible-in-subclauses

internal/stackql/router/parameter_router.go, internal/stackql/sqlengine/postgres_tcp.go, test/mockserver/expectations/static-gcp-expectations.json, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Fixed parameter cloning defect.
- Now support joins on `IN` subclause relations via subqueries.
- Added robot test `Select With Path Parameters inside IN Scalars Mixed With an Equals Parameter all inside WHERE Clause Returns Expected Result`.
- Added robot test `Select Subquery Join With Path Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
- Added robot test `Select Subquery Join With Parameters inside IN Scalars Plus More inside WHERE Clause Returns Expected Result`.
Closes #329 
- Added robot test `Select With Path Parameters inside IN Scalars Mixed With an Equals Parameter all inside WHERE Clause Returns Expected Result`.
- Added robot test `Select Subquery Join With Path Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
- Added …
=> mixed-in-subclause-parameter-routing

.github/goreleaser/.goreleaser-for-darwin.yaml, .github/goreleaser/.goreleaser-for-linux.yaml, .github/goreleaser/.goreleaser-for-windows.yaml, .github/workflows/build.yaml
**Added Goreleaser**
- This build uses three different files (each for a different platform) because, as mentioned in [this comment](https://github.com/stackql/stackql/issues/224#issuecomment-1817294807), StackQL needs to enable CGO. To avoid issues with cross-compiling and CGO, the binary needs to be built with different compilers (`CC` and `CXX`) for each platform.
- Utilizes [goreleaser-action](https://github.com/goreleaser/goreleaser-action) in `build.yaml` to build the binary.
- Triggered by the `tags` event and hasn't affected the main workflows.
Goreleaser build includes:
- Windows AMD64
- Darwin universal binary ARM64 and AMD64
- Linux AMD64 and ARM64
- Linux packages `.deb`, `.rpm`, `.apk`, and Archlinux packages
Excluded:
- Docker images
- Chocolatey Windows packages
The reason …
=> feat: add goreleaser

cicd/requirements.txt, internal/stackql/acid/tsm/tsm.go, internal/stackql/acid/tsm_physio/access_methods.go, internal/stackql/acid/tsm_physio/best_effort_coordinator.go, internal/stackql/acid/tsm_physio/best_effort_orchestrator.go, internal/stackql/acid/tsm_physio/buffer_pool.go, internal/stackql/acid/tsm_physio/coordinator.go, internal/stackql/acid/tsm_physio/lazy_coordinator.go, internal/stackql/acid/tsm_physio/lock_manager.go, internal/stackql/acid/tsm_physio/log_manager.go, internal/stackql/acid/tsm_physio/statement.go, internal/stackql/acid/tsm_physio/tsm_implementation.go, internal/stackql/acid/tsm_physio/txn_orchestrator.go, internal/stackql/acid/tsm_physio/txn_provider.go, internal/stackql/driver/driver.go, internal/stackql/handler/handler.go, internal/stackql/httpmiddleware/httpmiddleware.go, test/mockserver/README.md
- This is a technical change, function unchanged, interfaces altered to support upcoming functions.
- Added Transaction Storage Manager (TSM) placeholder with access to sites of mutation.
- Separate interface from implementation to avoid import cycles.
- ACID ideation based upon ARIES and canonical RDBMSs.
- Updated linter.
- Pin `psycopg` versions due to OS runner error on some regression in `psycopg[binary]==3.1.15`.
#212 
New TSM interface is stable in `stackql`; all automated tests pass.
N/A.
=> transaction-storage-manager-pattern

internal/stackql/dependencyplanner/dependencyplanner.go, internal/stackql/drm/prepared_statement_args.go, internal/stackql/responsehandler/responsehandler.go, internal/stackql/router/parameter_router.go, test/mockserver/expectations/static-gcp-expectations.json, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Fix defect that caused nil result sets inside `IN` subclause responses to fail most of the time.
- Remove spurious control parameter serialization.
- Expand control parameter equivalency to cover selections.
- Added robot test `Select Subquery Join With Path Parameters inside IN Scalars Including Empty inside WHERE Clause Returns Expected Result`.
#314 
- Added robot test `Select Subquery Join With Path Parameters inside IN Scalars Including Empty inside WHERE Clause Returns Expected Result`.
N/A.
=> in-clause-defects

cicd/requirements.txt
- Following on from buggy `psycopg` version `3.1.15` failures, we will resume a protected aggressive track.
N/A.
All automated tests pass, whereas when `psycopg` was set to version `3.1.15`, the `MacOS Build` .
N/A.
=> aggressive-dependency-versioning

.github/workflows/go.yml, cicd/ref/bench/baseline-go-bench.log, cicd/ref/bench/max-threshold-go-bench.log, internal/stackql/driver/driver_bench_test.go, test/registry/src/aws/v0.1.0/services/pseudo_s3.yaml
- Benchmark tests without plan cache.
- Benchmark tests statistics collection.
- Idiomatic `yaml` strings in doc-based views example.
- Diagnostics and thresholds.
- Comparison against historical benchmark baseline.
- Comparison against arbitrary benchmark maximum threshold.
- Becnhmark CI step enforces max threshold compliance.
#314 
From a previous run in a private repository, wherein the benchmarks were **accidentally** compared against historical baseline rather than hard limits, the below output proves that threshold overrun generates the desired CI failure:
```
pkg: github.com/stackql/stackql/internal/stackql/driver
│ cicd/ref/bench/baseline-go-bench.log │ cicd/log/current-bench-nocache.txt  │
│                sec/op                │    sec/op     vs base               │ …
```
=> intelligent-bench

test/robot/functional/stackql_sessions.robot, test/robot/lib/StackQLInterfaces.py
- Added robot test `High Volume IN Query Is Correct and Performs OK`.
- This test serves as a benchmark for a realistic multi cloud query scenario.
- At this stage, test only applies where comncurrency settings are aggressive.
- Limits are pretty conservative, can revisit once more real world data has been gathered.
Closes #314 
- Added robot test `High Volume IN Query Is Correct and Performs OK`.
N/A.
=> external-benchmark

internal/stackql/provider/auth_util.go, test/mockserver/expectations/static-auth-testing-expectations.json, test/robot/functional/stackql.resource
- Fix bug where parent token was attached to all children in `custom` auth.
- Uplift header verification for robot test `Custom Auth Linear Should Send Appropriate Credentials`, in order to ensure correct functionality.
- Uplift header verification for robot test `Custom Auth Linear Should Send Appropriate Credentials`, in order to ensure correct functionality.
N/A.
=> successor-token-repeat-patch

internal/stackql/astvisit/param_extract.go, internal/stackql/astvisit/placeholder_param_extract.go, internal/stackql/dataflow/collection.go, internal/stackql/dataflow/edge.go, internal/stackql/parserutil/parameter_metadata.go, internal/stackql/parserutil/table_parameter_coupling.go, internal/stackql/primitivebuilder/dependent_recursive.go, internal/stackql/router/parameter_router.go, internal/stackql/sql_system/sql/postgres/sqlengine-setup.ddl, internal/stackql/sql_system/sql/sqlite/sqlengine-setup.ddl, test/robot/functional/stackql_mocked_from_cmd_line.robot, test/robot/lib/StackQLInterfaces.py
- Added logic to enable dynamic view `where` parameter overwrite, deterministically.
- Added robot test `Mutable View Select With Path Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
- Streamlined dependency graph edge assembly.
- Added robot test `Mutable View Select With Path Parameters inside IN Scalars inside WHERE Clause Returns Expected Result`.
N/A.
This change does not alter technical debt significantly.  From a certain point of view, the late binding clobber of view `where` clause parameters, which is **NOT** `sql`-native, is an unnecessary liability and therefore technical debt.  And this change supports same.
=> indirect-placeholders

internal/stackql/astanalysis/selectmetadata/select_metadata_test.go
- add unit testing for package `internal/stackql/astanalysis/selectmetadata`
Fix issue #289
=> feat(unit-test): add unit test for package selectmetadata

go.mod, go.sum, internal/stackql/datasource/sql_datasource/generic.go, internal/stackql/datasource/sql_datasource/generic_test.go, internal/stackql/datasource/sql_datasource/sql_datasource.go, internal/stackql/datasource/sql_datasource/sql_datasource_test.go, internal/stackql/entryutil/entryutil.go
- add implementation for testing sql_datasource.go
- modify sql_datasource.go by adding function for dependency injection
- add implementation for testing generic.go
- modify generic.go by adding variable for patching GetDB function
- modify entryutil.go to adjust sql_datasource.go
- include new package DATA-DOG/go-sqlmock
Fix issue #299
=> feat(unit-test): add unit testing for package sql_datasource

test/robot/functional/stackql_sessions.robot
Summary:
- Avoid piping in `robot`invocations with standard shells.
- Broadened effected tests to cover windows.
- Uplift for robot test `Acceptable Secure PSQL Connection to mTLS Server With Diagnostic Query Returns Connection Info`.
- Uplift for robot test `Unacceptable Insecure PSQL Connection to mTLS Server Returns Error Message`.
Closes #365 
- Uplift for robot test `Acceptable Secure PSQL Connection to mTLS Server With Diagnostic Query Returns Connection Info`.
- Uplift for robot test `Unacceptable Insecure PSQL Connection to mTLS Server Returns Error Message`.
N/A.
This change does not introduce technical debt.  Quite the opposite; it reduces technical debt.
=> shell-orchestration-in-robot

internal/stackql/dto/auth_ctx.go, internal/stackql/provider/auth_util.go
Updates to enable optional `AWS_SESSION_TOKEN` variable, when present this is used with the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as part of the cred signing request
None
Will test both scenarios
None
None
=> updated `aws` auth to support `sts assume role` creds

internal/stackql/astanalysis/earlyanalysis/first_passes.go, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Materialized views can support non standard relations.
- Added robot test `Create and Interrogate Materialized View With Userspace Table Join and Aliasing and Name Collision`.
N/A.
- Added robot test `Create and Interrogate Materialized View With Userspace Table Join and Aliasing and Name Collision`.
N/A.
This change skips a `PG internal` analysis step for materialized views.
=> materialized-views-plus-non-standard-relations

internal/stackql/sql_system/postgres.go, internal/stackql/sql_system/sqlite.go, internal/stackql/sqlengine/postgres_tcp.go, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Inline `SELECT... UNION SELECT...` supported.
- Added robot test `Inline Union Select Returns Expected Result`.
N/A.
- Added robot test `Inline Union Select Returns Expected Result`.
- [\x] Linter passes locally, as per [the developer guide](/docs/developer_guide.md#linting).
N/A.
This change in itself does not introduce technical debt.
=> union-select-inline

internal/stackql/drm/drm_cfg.go, internal/stackql/internal_data_transfer/internaldto/heirarchy_identifiers.go, internal/stackql/sqlrewrite/sqlrewrite.go, internal/stackql/tablemetadata/extended_table_metadata.go, internal/stackql/taxonomy/hierarchy.go, test/robot/functional/stackql_mocked_from_cmd_line.robot
Summary:
- Support for unions of materialized views in materialized views.
- Added robot test `Create Then Replace and Interrogate Materialized View With Union of Materialized Views`.
=> regression-coverage-expansion

CODE_OF_CONDUCT.md, CONTRIBUTING.md, internal/stackql/httpmiddleware/httpmiddleware.go, test/mockserver/expectations/static-aws-expectations.json, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Added Code of Conduct.
- Support for eager print of HTTP response body on discernable error, by default.
- Added robot test `Response Body Printed by Default on Error`.
- Amended robot test `Transaction Abort Attempted Commit Digitalocean Insert Droplet` to conform with new eager, verbose default pattern.
Closes #388 
- Added robot test `Response Body Printed by Default on Error`.
- Amended robot test `Transaction Abort Attempted Commit Digitalocean Insert Droplet` to conform with new eager, verbose default pattern.
N/A.
=> community-support

.github/workflows/go.yml, .vscode/launch.json, Dockerfile, cicd/vol/postgres/.gitignore, cicd/vol/stackql/test/.gitignore, docker-compose-persist-postgres.yml, docker-compose.yml, internal/stackql/astvisit/from_rewrite.go, internal/stackql/cmd/root.go, internal/stackql/drm/drm_cfg.go, internal/stackql/dto/dto.go, internal/stackql/dto/runtime_ctx.go, internal/stackql/entryutil/entryutil.go, internal/stackql/handler/handler.go, internal/stackql/internal_data_transfer/internaldto/materialized_view_dto.go, internal/stackql/internal_data_transfer/internaldto/physical_table_dto.go, internal/stackql/internal_data_transfer/internaldto/view_dto.go, internal/stackql/parserutil/parser_util.go, internal/stackql/primitivebuilder/ddl.go, internal/stackql/sql_system/postgres.go, internal/stackql/sql_system/sql_system.go, internal/stackql/sql_system/sqlite.go, test/robot/functional/stackql.resource, test/robot/functional/stackql_export.robot, test/robot/lib/StackQLInterfaces.py, test/robot/lib/stackql_context.py
- Export materializations to their own schema / namespace, configurably.
- Publish `materialized view` relations to dedicated namespace.
- Added robot test `Export Materialized View and then Access From RDBMSs`.
- Added robot test `Export Materialized View and then Access From RDBMSs Over Stackql Postgres Server`.
- Added `sqlite3` to docker testing image.
- Added `sqlite` to windows testing image.
- Works for both `postgres` and `sqlite` backends, using schema and dot-delimited table names, respectively.
N/A.
- Added robot test `Export Materialized View and then Access From RDBMSs`.
- Added robot test `Export Materialized View and then Access From RDBMSs Over Stackql Postgres Server`.
N/A.
=> export-materializations-v01

internal/stackql/sql_system/postgres.go, internal/stackql/sql_system/sqlite.go, test/robot/functional/stackql_export.robot
- Support for export of user space tables.
- Added robot test `Export User Space Table and then Access From RDBMSs`.
- Added robot test `Export User Space Table and then Access From RDBMSs Over Stackql Postgres Server`.
- Postgres logic adjusted.
- Identified bug: One statement per psql string only at this stage.
N/A.
- Added robot test `Export User Space Table and then Access From RDBMSs`.
- Added robot test `Export User Space Table and then Access From RDBMSs Over Stackql Postgres Server`.
N/A.
=> export-expanded

.vscode/launch.json, internal/stackql/drm/drm_cfg.go, internal/stackql/primitivebuilder/ddl.go, internal/stackql/sql_system/postgres.go, internal/stackql/sql_system/sql_system.go, internal/stackql/sql_system/sqlite.go, test/robot/functional/stackql_export.robot
- Support for basic lifecycle of exported relations.
- Added robot test `Lifecycle Export Materialized View and then Access From RDBMSs`.
- Added robot test `Lifecycle Export Materialized View and then Access From RDBMSs Over Stackql Postgres Server`.
- Added robot test `Lifecycle Export User Space Table and then Access From RDBMSs`.
- Added robot test `Lifecycle Export User Space Table and then Access From RDBMSs Over Stackql Postgres Server`.
N/A.
- Added robot test `Lifecycle Export Materialized View and then Access From RDBMSs`.
- Added robot test `Lifecycle Export Materialized View and then Access From RDBMSs Over Stackql Postgres Server`.
- Added robot test `Lifecycle Export User Space Table and then Access From RDBMSs`.
- Added robot test `Lifecycle Export User Space Table and then …
=> export-relation-life-cycle

test/mockserver/expectations/static-aws-expectations.json, test/registry/src/aws/v0.1.0/services/pseudo_s3.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Adjusted `s3` hybrid resource insert API to match reality.
- Amended request payload and expectation for robot test `AWS Hybrid Service Cloud Control S3 Bucket Insert Defaulted`.
- Amended request payload and expectation for robot test `AWS Hybrid Service Cloud Control S3 Bucket Insert Dynamic`.
N/A.
- Amended request payload and expectation for robot test `AWS Hybrid Service Cloud Control S3 Bucket Insert Defaulted`.
- Amended request payload and expectation for robot test `AWS Hybrid Service Cloud Control S3 Bucket Insert Dynamic`.
N/A.
=> real-world-s3-hybrid-insert

.vscode/launch.json, internal/stackql/primitivebuilder/single_select_acquire.go, test/mockserver/expectations/static-gcp-expectations.json, test/registry/src/googleapis.com/v0.1.2/services/cloudkms-v1.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Empty response will generate empty table, even in the face of `jsonpath` error.
- Added robot test `Empty Response 200 Missing Jsonpath Search Key Should Return Empty Table on GCP KMS Key Rings`.
- Added robot test `Normal Response 200 Should Return Populated Table on GCP KMS Key Rings`.
N/A.
- Added robot test `Empty Response 200 Missing Jsonpath Search Key Should Return Empty Table on GCP KMS Key Rings`.
- Added robot test `Normal Response 200 Should Return Populated Table on GCP KMS Key Rings`.
N/A.
=> empty-response-empty-table

go.mod, go.sum, internal/stackql/astvisit/param_extract.go, internal/stackql/dataflow/relation.go, internal/stackql/dependencyplanner/dependencyplanner.go, internal/stackql/docparser/doc_parser.go, internal/stackql/driver/driver.go, internal/stackql/internal_data_transfer/internaldto/db_table.go, internal/stackql/parserutil/parser_util.go, internal/stackql/primitivebuilder/single_select_acquire.go, internal/stackql/router/parameter_router.go, internal/stackql/sql_system/postgres.go, internal/stackql/sql_system/sql_system.go, internal/stackql/sql_system/sqlite.go, internal/stackql/sqlrewrite/sqlrewrite.go, internal/stackql/sqlstream/sql_map_stream.go, internal/stackql/taxonomy/annotation_context.go, test/mockserver/expectations/static-gcp-expectations.json, test/registry/src/googleapis.com/v0.1.2/services/cloudkms-v1.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Fixed error caused by scalar in ON condition.
- Deduplication in dataflows for `ON` conditions.
- Fix bug wherein data flow `ON` conditions with functions silently halt analysis.
- Added robot test `Left Outer Join Network Infra Scalar in ON Condition`.
- Added robot test `Left Outer Join Network Infra Enforce Dependency`.
- Added robot test `Verify Data Flow Replication in ON Conditions Is Mitigated Using Example of Networks Subnetworks Join Aggregate`.
- Added robot test `Verify Data Flow ON Conditions With Functions Do NOT Halt Analysis Using Example of GCP KMS Keyrings to Keys Join`.
N/A.
- Added robot test `Left Outer Join Network Infra Scalar in ON Condition`.
- Added robot test `Left Outer Join Network Infra Enforce Dependency`.
- Added robot test `Verify Data Flow Replication in …
=> join-dependency-corner-cases

internal/stackql/parserutil/parser_util.go, internal/stackql/primitivegenerator/statement_analyzer.go, internal/stackql/router/parameter_router.go, internal/stackql/taxonomy/hierarchy.go, test/mockserver/expectations/static-aws-expectations.json, test/registry/src/aws/v0.1.0/provider.yaml, test/registry/src/aws/v0.1.0/services/acmpca.yaml, test/registry/src/aws/v0.1.0/services/cloud_control.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for exclusive views.
- Support for `postgres` function `json_extract_path_text` enhanced.
- Added robot test `Describe Extended Works For Single Exclusive View Through Naive Approach`.
- Added robot test `List And Details Dataflow View Works As Exemplified By AWS EC2 VPC Cloud Control`.
N/A.
- Added robot test `Describe Extended Works For Single Exclusive View Through Naive Approach`.
- Added robot test `List And Details Dataflow View Works As Exemplified By AWS EC2 VPC Cloud Control`.
N/A.
No technical debt is introduced in this change.  However the discovered technical debt that `Same resource, different method inside same query is not supported` has now been added to [the tech debt register](https://github.com/stackql/stackql/wiki/Tech-Debt-Register).
=> describe-and-dataflow-enhancement

test/mockserver/expectations/static-aws-expectations.json, test/registry/src/aws/v0.1.0/services/ec2.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- `ec2` lifecycle methods through no code changes.
- Added robot test `AWS EC2 Insert Start Instance Exemplifies Lifecycle Insert Verb Form Encoded Request`.
- Added robot test `AWS EC2 Update Start Instance Exemplifies Lifecycle Update Verb Form Encoded Request`.
N/A.
- Added robot test `AWS EC2 Insert Start Instance Exemplifies Lifecycle Insert Verb Form Encoded Request`.
- Added robot test `AWS EC2 Update Start Instance Exemplifies Lifecycle Update Verb Form Encoded Request`.
N/A.
=> lifecycle-ec2

internal/stackql/dataflow/collection.go, internal/stackql/dependencyplanner/dependencyplanner.go, internal/stackql/parserutil/parameter_metadata.go, internal/stackql/router/combination_composer.go, internal/stackql/router/parameter_router.go, internal/stackql/tablemetadata/extended_table_metadata.go, internal/stackql/taxonomy/annotation_context.go, test/mockserver/expectations/staging.json, test/mockserver/expectations/static-gcp-expectations.json, test/registry/src/googleapis.com/v0.1.2/services/cloudkms-v1.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot, test/robot/lib/StackQLInterfaces.py
- Support for >1 dataflow dimensions through `IN` clauses.
- Prime motivation is per-project, per-locality queries in `google`.
- Added robot test `Poly Dependency In Clause Split of List And Sublist Dimensions Dataflow View Works As Exemplified By AWS KMS Key Cloud Control`.
- Added robot test `Materialized View Beware Keywords of Poly Dependency In Clause Split of List And Sublist Dimensions Dataflow View Works As Exemplified By AWS KMS Key Cloud Control`.
N/A.
- Added robot test `Poly Dependency In Clause Split of List And Sublist Dimensions Dataflow View Works As Exemplified By AWS KMS Key Cloud Control`.
- Added robot test `Materialized View Beware Keywords of Poly Dependency In Clause Split of List And Sublist Dimensions Dataflow View Works As Exemplified By AWS KMS Key Cloud …
=> multi-data-flow

internal/stackql/sql_system/sqlite.go
Summary:
- Prevents failure scenario where calls to a non existent view trigger crash rather than JIT view creation.
- Untested hotfix.
No evidence is provided for this fix.  Same will be added ASAP.
=> hotfix-bigtime

internal/stackql/dataflow/component.go, internal/stackql/dependencyplanner/dependencyplanner.go, internal/stackql/dependencyplanner/stream_collection.go, internal/stackql/drm/drm_cfg.go, internal/stackql/httpmiddleware/httpmiddleware.go, internal/stackql/primitivebuilder/single_select_acquire.go, internal/stackql/sqlengine/sqlite_embedded.go, internal/stackql/sqlstream/sql_map_stream.go, internal/stackql/streaming/map_stream_collection.go, pkg/maths/common_maths.go, test/mockserver/expectations/static-azure-expectations.json, test/registry/src/azure/v0.1.0/services/key_vault.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for dataflow graphs with in degrees > 1 and out degreees > 1.
- Deduplicate dataflow graph node ordering.
- Split dataflow analysis passes.
- Number of builders corrected, in theory.
- Lifetime of tracking stores changed.
- Do not stop the world on streamed input generating 404s.
- Added robot test `Multi Dependency List And Detail Dataflow Works As Exemplified By Azure Vault and Keys and Key Details`.
- Added robot test `Multi Dependency Multiple List And Detail Dataflow Works As Exemplified By Azure Vault and Keys and Key Details`.
- Added robot test `Multi Dependency Multi Dependent Multiple List And Detail Dataflow Works As Exemplified By Azure Vault and Keys and Key Details`.
N/A.
- Added robot test `Multi Dependency List And Detail Dataflow Works As Exemplified By Azure …
=> multiple-dataflows-departing-and-arriving

internal/stackql/cmd/root.go
- Increase default maximum numbers of permitted dataflow dependencies and components.
N/A.
- All existing tests pass under new default configuration.  In truth some already employed aggressive dataflow parameters.  These are unaffected.
=> increase-dataflow-defaults

test/mockserver/expectations/static-azure-expectations.json, test/registry/src/azure/v0.1.0/services/network.yaml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support for polymorhpic self join.  this is highly useful for analytics.
- Added robot test `Self Join Polymorphic Works As Exemplified By Azure VPN List and Details`.
N/A.
- Added robot test `Self Join Polymorphic Works As Exemplified By Azure VPN List and Details`.
N/A.
=> test-coverage-self-join-polymorphic

internal/stackql/primitivegenerator/select.go, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Support unaliased projection on views and subqueries.
- Added robot test `Unaliased Projection on Materialized View as Exemplified by Google Firewalls`.
- Added robot test `Unaliased Projection on View as Exemplified by Google Firewalls`.
- Added robot test `Unaliased Projection on Subquery as Exemplified by Google Firewalls`.
N/A.
- Added robot test `Unaliased Projection on Materialized View as Exemplified by Google Firewalls`.
- Added robot test `Unaliased Projection on View as Exemplified by Google Firewalls`.
- Added robot test `Unaliased Projection on Subquery as Exemplified by Google Firewalls`.
N/A.
No new technical debt is introduced in this change.
=> indirection-symbol-collision

internal/stackql/parser/parse_test.go
Added unit testing for `internal/stackql/parse` pacakge
[#246](https://github.com/stackql/stackql/issues/246)
=> Add unit testing for `parse` package

docs/developer_guide.md, test/robot/functional/stackql_sessions.robot, test/robot/lib/stackql_context.py
- `psql` connection driven by env vars.
- Added robot test `Acceptable Password Only PSQL Connection Defined by Env Vars to Server With Diagnostic Query Returns Connection Info`.
- Added robot test `Acceptable Secure PSQL Connection Defined by Env Vars to mTLS Server With Diagnostic Query Returns Connection Info`.
- Added robot test `Acceptable Password Only PSQL Connection Defined by Env Vars to Server With Diagnostic Query Returns Connection Info`.
- Added robot test `Acceptable Secure PSQL Connection Defined by Env Vars to mTLS Server With Diagnostic Query Returns Connection Info`.
N/A.
=> psql-and-env-vars

internal/stackql/sqlcontrol/sqlcontrol_test.go
Added unit testing for internal/stackql/sqlcontrol pacakge
Closes #265
=> add unit testing for sqlcontrol package

internal/stackql/presentation/presentation.go, internal/stackql/writer/writer.go
- Bugfix for shell display of `%` user input.
This is lacking; we do not have a test harness for shell display.
Anecdotally, this is the errant behaviour for shell input `show services in google like '%';`, the display shows:
```
show services in google like '%!'(MISSING);
```
...and this is the fix:
```
show services in google like '%';
```
- Evidence is lacking; we do not have a test harness for shell display.
- This change does not *introduce* technical debt, however we should add a test harness for shell display.
=> percent-render

.github/actionlint.yaml, .github/workflows/build.yml, cicd/python/build.py, docs/CICD.md, test/robot/functional/__init__.robot, test/robot/lib/stackql_context.py, test/robot/reports/.gitignore
- Prelude to mega robust product.
- New `k8s.core_v1` release candidate.
- Amended query supporting robot test `K8S Nodes Select Leveraging` JSON Path for updated `k8s.core_v1 interface.
- Send kill signal to destroy al web servers in CI.
N/A.
- Amended query supporting robot test `K8S Nodes Select Leveraging` JSON Path for updated `k8s.core_v1 interface.
N/A.
No technical debt is here introduced, however:
- It has been found that future versions of the `mockserver` `jar` file are incompatible with the `VELOCITY` template bodies currently in use with versioon `5.12.0`.  Even a migration to `5.13.0` is breaking.  Have created [this ticket](https://github.com/stackql/stackql/issues/478) to deal with the issue.
=> k8s-provider-automation

internal/stackql/astformat/ast_format_test.go
…ring. Very sparse coverage for PostgresSelectExprsFormatting since I couldn't find a constructor for the ColIdent, ColName, and other SQLNode types.
Added sparse unit testing for astformat.PostgresSelectExprsFormatting and astformat.String. Very sparse coverage for PostgresSelectExprsFormatting since I couldn't find a constructor for the ColIdent, ColName, and other SQLNode types.
Closes #285 
Added 2 test functions
N/A
If parser.ParseQuery or the function's in astformat's signature or return changed significantly, these methods would most likely break.
If parser.ParseQuery functionality is even slightly modified, the asserts would fail, but this could be fixed very easily, since the assert compare the strings and have no logic to allow different case of ' vs "
Test has sparse coverage. …
=> Added unit testing for astformat

docker-compose-persist-postgres.yml, docker-compose.yml, test/robot/functional/stackql_mocked_from_cmd_line.robot
- Empower host-side deletion for `stackql` docker container mounted directories by running these containers as the host user.
- `postgres` server container user not addressed at this time.
- Teadown now active and working for robot test `Alternate App Root Persists All Temp Materials in Alotted Directory`.
- Remaining robot tests continue to work post changes.
N/A.
- Teadown now active and working for robot test `Alternate App Root Persists All Temp Materials in Alotted Directory`.
- Remaining robot tests continue to work post changes.
N/A.
=> docker-ownership-debt-reduction

.github/workflows/build.yml, docs/CICD.md
1. Due to shortfall in `docker` build tooling, it is not possible to first build and store a multi-architecture image and then test it and then push it.
2. Because point (1) is exactly what we require, and the prior push step has to halt and wait for `arm64`, time gets wasted.
3. This change seeks to mitigate same by pushing a digest-only tagged image for each architecture, and then (post-testing) adding *nominally* immutable multi-architecture tags.
**Note**: unfortunately, at this time, `linux/arm64` GHA runners are not first class citizens.  Once they are, there is significant potential improvement in build time
compared to current QEMU pattern.
https://github.com/stackql/stackql/issues/393
- Test battery continues to fiunction and report results.
- Docker images persisted as expected …
=> docker-build-parallel

.github/actionlint.yaml, .github/workflows/build.yml, docs/CICD.md
- Short term fix to avoid defective github action runner.
- Non standard runnner version pin.
N/A.
- All tests pass.
- Private repository build succeeds for docker `arm64` per below screen grab.
N/A.
- This does not accrue technical debt.
- That said,
=> busted-gha-ubuntu-docker

test/robot/functional/stackql_mocked_from_cmd_line.robot, test/robot/integration/stackql_integration_from_cmd_line.robot, test/robot/lib/StackQLInterfaces.py
- Added new robot testing keyword `Should Stackql Exec Inline Contain Both Streams`.
- Updated selected positive and negative scenarios to use new keyword.
- Robot test `Registry Pull Google Provider Implicit Latest Version` uses new keyword for positive scenario.
- Robot test `Select Star of EC2 Instances Returns Expected Result` uses new keyword for positive scenario.
- Robot test `Faulty Auth Azure Authenticated VM Sizes` uses new keyword for negative scenario.
N/A.
- Robot test `Registry Pull Google Provider Implicit Latest Version` uses new keyword for positive scenario.
- Robot test `Select Star of EC2 Instances Returns Expected Result` uses new keyword for positive scenario.
- Robot test `Faulty Auth Azure Authenticated VM Sizes` uses new keyword for negative scenario.
N/A.
No …
=> test-contains-both-streams
